### ISSUE TITLE
:sparkles: It site translations

### ISSUE THREAD

**Issue by omartek** [ct-js/ct-js-site#26]
What about translating in italian?
It's all in tree/master/src/_data/i18n?

**Comment by CosmoMyzrailGorynych** [comment]
It will also need an `it` directory, similarly to these:

![image](https://user-images.githubusercontent.com/3174357/187147332-54eb80b4-ca54-44b3-9697-5ff1f0208ac9.png)

**Comment by omartek** [comment]
Ok done.
