### ISSUE TITLE
Downloads page leads to the outdated web installer

### ISSUE THREAD

**Issue by vintprox** [ct-js/ct-js-site#47]
[Downloads](https://ctjs.rocks/download/) reveal the web installer for Linux, but the link leads to release `v1.0.0`, which isn't right. Replace this with `latest`, I guess.

This confusion has resulted in me downloading the wrong installer and getting what looks like an out-of-date bug: https://github.com/ct-js/ct-js/issues/523

I wonder if there is even a modern web installer to this day?

**Comment by vintprox** [comment]
Turns out web installer is another repo altogether, I didn't look enough into the link and the version is right.

https://github.com/leedigital/ct.js-launcher-in-shell-script

Well, that bug I've had is not out-of-date then.

**Comment by CosmoMyzrailGorynych** [comment]
Releases info is pulled from GitHub API every time ctjs.rocks is built, and the needed file is picked from the latest release by its extension. It is guaranteed to be the latest one.
